version: '3'

networks:
  takeaway:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: takeaway-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - takeaway

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: takeaway-php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - takeaway

  composer:
    image: composer:latest
    container_name: takeaway-composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - takeaway

  npm:
    build:
      context: .
      dockerfile: ./docker/npm/Dockerfile
    container_name: takeaway-npm
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/html
    entrypoint: ['npm']
    networks:
      - takeaway
